export const SET_LOADING = 'SET_LOADING';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const RESET_SEARCH = 'RESET_SEARCH';

export const RESET_BOOK_ERROR = 'RESET_BOOK_ERROR';

export const SET_USER = 'SET_USER';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR';

export const FETCH_SINGLE_BOOK_SUCCESS = 'FETCH_SINGLE_BOOK_SUCCESS';
export const FETCH_SINGLE_BOOK_ERROR = 'FETCH_SINGLE_BOOK_ERROR';
